import type { Metadata } from 'next'
import AuthHeader from '@/_components/header/AurhHeader'
export const metadata: Metadata = {
  title: 'Authentication Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <AuthHeader />
      <section>{children}</section>
    </>
  )
}
